# Generated by Django 3.0.4 on 2020-05-11 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_companyprofile_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Numer')),
                ('insurance_type', models.CharField(max_length=50, verbose_name='Rodzaj ubezpieczenia')),
                ('insurance_company', models.CharField(max_length=250, verbose_name='Ubezpieczyciel')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia')),
                ('expiry_date', models.DateField(verbose_name='Data zakończenia')),
                ('insurance_cost', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Koszt ubezpieczenia')),
                ('payment_type', models.CharField(max_length=50, verbose_name='Sposób zapłaty')),
                ('insurance_owner', models.CharField(max_length=250, verbose_name='Ubezpieczający')),
                ('vehicule_owner', models.CharField(max_length=250, verbose_name='Właściciel pojazdu')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CompanyProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_number', models.IntegerField(verbose_name='Numer raty')),
                ('rate_date', models.DateField(verbose_name='Data raty')),
                ('rate_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Kwota do zapłaty')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurances.Insurance')),
            ],
        ),
    ]
