# Generated by Django 3.0.4 on 2020-06-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='owner',
        ),
    ]
