export const GET_PROFILES = "GET_PROFILES";

export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_VEHICULES = "GET_VEHICULES";
export const ADD_VEHICULE = "ADD_VEHICULE";
export const DELETE_VEHICULE = "DELETE_VEHICULE";

export const GET_INSURANCES = "GET_INSURANCES";
export const ADD_INSURANCE = "ADD_INSURANCE";
export const DELETE_INSURANCE = "DELETE_INSURANCE";
