# Generated by Django 3.0.4 on 2020-10-31 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driving_license_number',
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.IntegerField(verbose_name='Numer prawa jazdy')),
                ('license_series', models.CharField(max_length=12, verbose_name='Seria prawa jazdy')),
                ('issue_date', models.DateField(verbose_name='Data wydania')),
                ('expiry_date', models.DateField(verbose_name='Data ważności')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverIDCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(verbose_name='Numer dowodu tożsamości')),
                ('id_series', models.CharField(max_length=12, verbose_name='Seria dowodu tożsamości')),
                ('issue_date', models.DateField(verbose_name='Data wydania')),
                ('expiry_date', models.DateField(verbose_name='Data waznosci')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver')),
            ],
        ),
    ]
