# Generated by Django 3.0.4 on 2020-04-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='address',
            field=models.CharField(default='ulica', max_length=100, verbose_name='Adres rejestracji'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='allowed_group_weight',
            field=models.IntegerField(default=1, verbose_name='Dopuszczalna masa zespołu pojazdów'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='allowed_weight',
            field=models.IntegerField(default=1, verbose_name='Dopuszczalna masa całkowita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine_power',
            field=models.IntegerField(default=1, verbose_name='Moc silnika'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine_power_netto',
            field=models.FloatField(default=1, verbose_name='Moc netto silnika'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine_v',
            field=models.FloatField(default=1, verbose_name='Pojemność silnika'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='olej napedowy', max_length=30, verbose_name='Rodzaj paliwa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='homologation_number',
            field=models.CharField(default='4', max_length=100, verbose_name='Numer świadectwa homologacji'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='max_weight',
            field=models.IntegerField(default=1, verbose_name='Maksymalna waga całkowita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='max_wtrailer',
            field=models.IntegerField(default=1, verbose_name='Masa całkowita przyczepy bez hamulca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='max_wtrailer_break',
            field=models.IntegerField(default=1, verbose_name='Masa całkowita przyczepy z hamulcem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=1, verbose_name='Przebieg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='pesel',
            field=models.CharField(default='4567893456', max_length=15, verbose_name='Pesel/Regon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='reg_owner',
            field=models.CharField(default='foo', max_length=50, verbose_name='Pierwszy właściciel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='seat_number',
            field=models.IntegerField(default=1, verbose_name='Ilość miejsc siedzących'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='stand_number',
            field=models.IntegerField(default=1, verbose_name='Ilość miejsc stojących'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='total_weight',
            field=models.IntegerField(default=1, verbose_name='Masa własna pojazdu'),
            preserve_default=False,
        ),
    ]
