# Generated by Django 3.0.4 on 2020-05-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalinspection',
            name='vehicule',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehiculecard',
            name='vehicule',
        ),
        migrations.DeleteModel(
            name='RegistrationCertificate',
        ),
        migrations.DeleteModel(
            name='TechnicalInspection',
        ),
        migrations.DeleteModel(
            name='Vehicule',
        ),
        migrations.DeleteModel(
            name='VehiculeCard',
        ),
    ]
