# Generated by Django 3.0.4 on 2020-05-22 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_auto_20200518_2056'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicules', '0002_auto_20200522_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=8, verbose_name='Number rejestracyjny')),
                ('vehicule_brand', models.CharField(max_length=150, verbose_name='Marka pojazdu')),
                ('vehicule_type', models.CharField(blank=True, max_length=30, verbose_name='Typ pojazdu')),
                ('vehicule_model', models.CharField(blank=True, max_length=30, verbose_name='Model pojazdu')),
                ('vin_number', models.CharField(max_length=17, unique=True, verbose_name='Numer nadwozia')),
                ('first_registration_date', models.DateField(verbose_name='Data pierwszej rejestracji')),
                ('registration_owner_name', models.CharField(max_length=250, verbose_name='Nazwa właściciela dowodu rejestracyjnego')),
                ('reg_owner_pesel_regon', models.IntegerField(verbose_name='Pesel, Regon właściciela dowodu rejestracyjnego')),
                ('reg_owner_address', models.CharField(max_length=250, verbose_name='Adres właściciela dowodu rejestracyjnego')),
                ('owner_name', models.CharField(max_length=250, verbose_name='Nazwa właściciela')),
                ('owner_pesel_regon', models.IntegerField(verbose_name='Pesel, Regon właściciela pojazdu')),
                ('owner_address', models.CharField(max_length=250, verbose_name='Adres właściciela pojazdu')),
                ('max_total_weight', models.IntegerField(blank=True, null=True, verbose_name='Maksymalna masa całkowita pojazdu')),
                ('perm_gross_weight', models.IntegerField(blank=True, null=True, verbose_name='Dopuszczalna masa całkowita pojazdu')),
                ('perm_gross_group', models.IntegerField(blank=True, null=True, verbose_name='Dopuszczalna masa całkowita zespołu pojazdów')),
                ('gross_weight', models.IntegerField(verbose_name='Masa własna pojazdu')),
                ('vehicule_category', models.CharField(blank=True, max_length=150, verbose_name='Kategoria pojazdu')),
                ('homologation_number', models.CharField(blank=True, max_length=45, verbose_name='Numer homologacji')),
                ('axle_count', models.IntegerField(verbose_name='Liczba osi')),
                ('trailer_total_break', models.IntegerField(blank=True, null=True, verbose_name='Maksymalna masa całkowita przyczepy z hamulcem')),
                ('trailer_total', models.IntegerField(blank=True, null=True, verbose_name='Maksymalna masa całkowita przyczepy bez hamulca')),
                ('engine_capacity', models.FloatField(blank=True, null=True, verbose_name='Pojemność silnika')),
                ('engine_power', models.FloatField(blank=True, null=True, verbose_name='Moc silnika')),
                ('fuel_kind', models.CharField(blank=True, max_length=30, verbose_name='Rodzaj paliwa')),
                ('power_to_weight', models.FloatField(blank=True, null=True, verbose_name='Stosunek mocy do masy własnej')),
                ('seat_count', models.IntegerField(blank=True, null=True, verbose_name='Liczba miejsc siedzących')),
                ('places_count', models.IntegerField(blank=True, null=True, verbose_name='Liczba miejsc stojących')),
                ('vehicule_kind', models.CharField(max_length=45, verbose_name='Rodzaj pojazdu')),
                ('vehicule_purpose', models.CharField(blank=True, max_length=45, verbose_name='Przeznaczenie pojazdu')),
                ('production_year', models.IntegerField(verbose_name='Rok produkcji')),
                ('allowed_package', models.IntegerField(blank=True, null=True, verbose_name='Dopuszczalna ładowność')),
                ('axle_pressure', models.FloatField(blank=True, null=True, verbose_name='Dopuszczalny nacisk na oś')),
                ('milage', models.IntegerField(blank=True, null=True, verbose_name='Przebieg')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CompanyProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pojazd',
                'verbose_name_plural': 'Pojazdy',
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='VehiculeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_series', models.CharField(max_length=3, verbose_name='Seria karty pojazdu')),
                ('card_number', models.IntegerField(verbose_name='Numer karty pojazdu')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.Vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='Data badania technicznego')),
                ('inspection_expiry', models.DateField(verbose_name='Data ważności badania technicznego')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.Vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_series', models.CharField(max_length=2, verbose_name='Seria dowodu rejestracyjnego')),
                ('cert_number', models.IntegerField(verbose_name='Numer dowodu rejestracyjnego')),
                ('release_date', models.DateField(verbose_name='Data wydania dowodu')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Data ważności dowodu')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicules.Vehicule')),
            ],
        ),
    ]
