# Generated by Django 3.0.4 on 2020-05-02 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200413_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('address_street', models.CharField(max_length=250)),
                ('address_number', models.CharField(max_length=150)),
                ('address_city', models.CharField(max_length=250)),
                ('address_zip', models.CharField(max_length=15)),
                ('company_website', models.CharField(max_length=250)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_phone2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=250)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='main.CompanyProfile')),
            ],
        ),
    ]
