# Generated by Django 3.0.4 on 2020-05-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_companyprofile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(default='PIS', max_length=250, verbose_name='Firma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='kaczor@pis.pl', max_length=254, verbose_name='Adres email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skype_number',
            field=models.CharField(default='56789', max_length=50, verbose_name='Numer skype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='imię'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=250, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone_number',
            field=models.CharField(max_length=50, verbose_name='Numer telefonu'),
        ),
    ]
